const users = [
  {
    username: "johndoe",
    password: "password123",
    role: "user",
    name: "John Doe",
    position: "Software Developer",
    phone: "555-555-5555",
    region: "North America",
    street: "123 Main St",
    city: "New York",
    zipCode: "10001",
    noteAddress: "Apartment 4B",
  },
  {
    username: "user1",
    password: "password123",
    role: "user",
    name: "John Smith",
    phone: "555-555-5555",
    region: "North America",
  },
  {
    username: "user2",
    password: "password123",
    role: "user",
    name: "Jane Doe",
    phone: "555-555-5555",
    region: "Europe",
  },
  {
    username: "admin1",
    password: "password123",
    role: "admin",
    name: "Sarah Johnson",
    phone: "555-555-5555",
    region: "North America",
  },
  {
    username: "admin2",
    password: "password123",
    role: "admin",
    name: "Mark Williams",
    phone: "555-555-5555",
    region: "Asia",
  },
  {
    username: "technician1",
    password: "password123",
    role: "technician",
    name: "David Lee",
    phone: "555-555-5555",
    region: "North America",
  },
  {
    username: "technician2",
    password: "password123",
    role: "technician",
    name: "Karen Wong",
    phone: "555-555-5555",
    region: "Australia",
  },
  {
    username: "manager1",
    password: "password123",
    role: "manager",
    name: "Steven Chen",
    phone: "555-555-5555",
    region: "North America",
  },
  {
    username: "user3",
    password: "password123",
    role: "user",
    name: "Thomas Smith",
    phone: "555-555-5555",
    region: "Africa",
  },
];

module.exports = users;
